### PR TITLE
Fix the RightSideRouterLinks problem + slight refactor

### LINKED ISSUE #51: rightSideRouterLinks is an empty array on user update
Currently, if you attempt to change any user settings (themes, auth), the usual buttons that allow you to access settings get hidden:
image

When user settings are updated, the "authService.onUserUpdate" method is executed. This is picked up by the "userWatcher" event.
image

In app.component.ts, the "userWatcher" event is checked for changes, if there are changes, the "handleUserUpdate" method is executed. this.rightSideRouterLinks is set to an empty array. 
image

For some reason, this.login is undefined at this point and the "this.rightSideRouterLinks.push" commands are not executed because of that. This causes the buttons to disappear.

Video:

https://github.com/LittleBigRefresh/refresh-web/assets/17880243/c46922ad-e964-4e6e-9e2f-b4bd569b8a86

### PR DESCRIPTION
**Pull request by speedyman08**
This pull request:
- Fixes #51 

Summary of changes:

- To guarantee that this.login's viewChild is defined before the this.handleUserUpdate method is called, i made 
AppComponent implement the AfterViewInit hook

- The GetInstanceInformation and theme stuff were moved to the AfterViewInit hook

- the rightSideRouterLink .push method calls were moved to a separate method

### CODE REVIEW

File: src/app/app.component.ts [hunk 1]
```diff
@@ -87,51 +87,57 @@ export class AppComponent {
...
+            if (this.themeService.IsThemingSupported()) {
+                const theme: string | null = localStorage.getItem("theme");
+                if (theme) {
+                    this.themeService.SetTheme(theme);
+                } else {
+                    this.themeService.SetTheme("default");
+                }
             }
-        }
+        });
```
Comment (jvyden) [inline src/app/app.component.ts:109]: This can probably stay in the constructor.

**Review by jvyden — COMMENTED** [review]
Looks OK at a glance, but I don't see the reason for moving theming stuff to AfterViewInit.

File: src/app/app.component.ts (hunk 1 above)
Comment (speedyman08) [reply src/app/app.component.ts:109]: It just made more sense to handle themes just after the html template was binded to AppComponent at the time of writing this pr, i'll revert this change now

**Review by jvyden — APPROVED** [review]
